name: Unit Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOJURE_INSTALL_PATH: ${{ github.workspace }}/clojure

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4 # https://github.com/actions/setup-java
        with:
          distribution: "temurin"
          java-version: "21"
      - name: cache Clojure installations
        uses: actions/checkout@v4
        with:
          path: |
            ${{ env.CLOJURE_INSTALL_PATH }}/bin/clojure
            ${{ env.CLOJURE_INSTALL_PATH }}/bin/clj
            ${{ env.CLOJURE_INSTALL_PATH }}/lib/clojure
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/bin/clojure', env.CLOJURE_INSTALL_PATH)) }}
      - name: install Clojure
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh --prefix $CLOJURE_INSTALL_PATH
      - name: tests
        run: ${{ env.CLOJURE_INSTALL_PATH }}/bin/clojure -X:test
